environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "6"

version: "{build}"
build: off
deploy: off

cache:
  - "%LOCALAPPDATA%/Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
  - node --version
  - yarn --version

test_script:
  - yarn test
